In [14]:
import numpy as np
from scipy.stats import bernoulli

In [ ]:
u = [0.4, 0.5, 0.7]

In [103]:
def initialize(N, T):
    """
    Parameters
    N - is the number of arms
    T - timesteps
    """
    H = np.zeros((T+2, N)) #2D Array telling number of times an arm has been played till round T
    Q = np.zeros((T+2, N)) #2D Array telling whether containing queue (can be made shorter)
    D = np.zeros((T+2, N)) #2D Array telling whether an arm was played in round T
    U = np.zeros((T+1, N))
    S_hat = np.zeros((T+1, N)) #2D Array storing the cumulated sum
    X = np.zeros((T+1, N))
    
    return H, Q, D, U, S_hat, X

def compute_utility_arm(X, t, i, D, H, S_hat):
    """
    Parameters
    X - 2D Array of rewards for arm across T
    t - time round
    i - arm index
    D - 2D array telling whether an arm is played in round i
    H - 
    """
    u_simple = 0
    
    u_simple = S_hat[t-1][i]/H[t-1][i]
    u = min(u_simple + np.sqrt((3*np.log(t))/(2*H[t-1][i])),1)
    return(u)

def find_arms(Q, U, t, eta, m):
    rewards = np.zeros(Q.shape[1])
    for i in range(Q.shape[1]):
        rewards[i] = Q[t][i] + eta*U[t][i]
    arms = np.argsort(rewards)[::-1][0:m]
    return(arms)
    
def LFG(N, T, R, Mu, eta, m = 1):
    """
    Parameters
    N - is the number of arms
    T - timesteps
    R - fraction telling number of times each arm has to be played
    """
    
    H, Q, D, U, S_hat, X = initialize(N, T)
    for t in range(0,T+1):
        for arm in range(N):
            if H[t-1][arm] > 0:
                U[t][arm] = compute_utility_arm(X, t, arm, D, H, S_hat)
            else:
                U[t][arm] = 1
            Q[t][arm] = max(Q[t-1][arm] + R[arm] - D[t-1][arm], 0)
        #print(S_hat)
        ### Finding arms with maximum objective
        arms = find_arms(Q, U, t, eta, m)
        
        D[t][arms] = 1
        for arm in arms:
            X[t][arm] = bernoulli.rvs(Mu[arm], size=1)[0]
        for arm in range(Mu.shape[0]):
            H[t][arm] = H[t-1][arm] + D[t][arm]
            S_hat[t][i] = S_hat[t-1][i] + X[t][i]
  #  regret = 
            
    return H,Q,D,U

In [93]:

H,Q,D,U = LFG(10, T, [0.05]*10, np.array(u), 1, 1)

In [104]:

H2,Q2,D2,U2 = LFG(10, 2, [0.05]*10, np.array(u), 1, 1)

In [105]:
print(U2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [5]:
u = [0.8]
for i in range(1,10):
    u.append(u[0]-(0.01*i))

In [91]:
T = int(1e6)

In [32]:
Reward_max = 0.05*T*np.sum(u)+0.5*T*u[0]
print(Reward_max)

777500.0


In [56]:
U[50]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])